# Created using wingetcreate 1.5.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.5.0.schema.json

PackageIdentifier: TopCat.MediocreMapAssistant2
PackageVersion: 4.8.4
PackageLocale: en-US
Publisher: Top_Cat
PublisherUrl: https://git.bsmg.dev/Top_Cat
PublisherSupportUrl: https://bsaber.com/getting-started/mapping/
Author: TopCat
PackageName: MMA2
PackageUrl: https://github.com/Top-Cat/MediocreMapAssistant2
License: MIT License
LicenseUrl: https://git.bsmg.dev/js/licenses.txt
ShortDescription: '"fork" of MediocreMapper by squeaksies which is a "fork" of EditSaberEnhanced by permissionBRICK which is a "fork" of EditSaber by Ikeiwa. Previously assisting with EditSaberEnhanced; A set of feature additions on EditSaberEnanced.'
ManifestType: defaultLocale
ManifestVersion: 1.5.0
